# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeform.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addEditCoffeeForm(object):
    def setupUi(self, addEditCoffeeForm):
        addEditCoffeeForm.setObjectName("addEditCoffeeForm")
        addEditCoffeeForm.resize(400, 300)
        self.saveButton = QtWidgets.QPushButton(addEditCoffeeForm)
        self.saveButton.setGeometry(QtCore.QRect(270, 260, 113, 32))
        self.saveButton.setObjectName("saveButton")
        self.label = QtWidgets.QLabel(addEditCoffeeForm)
        self.label.setGeometry(QtCore.QRect(80, 20, 60, 16))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(addEditCoffeeForm)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 111, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(addEditCoffeeForm)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 121, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(addEditCoffeeForm)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 121, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(addEditCoffeeForm)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 121, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(addEditCoffeeForm)
        self.label_6.setGeometry(QtCore.QRect(120, 230, 41, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(addEditCoffeeForm)
        self.label_7.setGeometry(QtCore.QRect(260, 230, 71, 16))
        self.label_7.setObjectName("label_7")
        self.idLineEdit = QtWidgets.QLineEdit(addEditCoffeeForm)
        self.idLineEdit.setGeometry(QtCore.QRect(160, 20, 211, 21))
        self.idLineEdit.setReadOnly(True)
        self.idLineEdit.setObjectName("idLineEdit")
        self.nameLineEdit = QtWidgets.QLineEdit(addEditCoffeeForm)
        self.nameLineEdit.setGeometry(QtCore.QRect(160, 40, 211, 21))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.roastLineEdit = QtWidgets.QLineEdit(addEditCoffeeForm)
        self.roastLineEdit.setGeometry(QtCore.QRect(160, 60, 211, 21))
        self.roastLineEdit.setObjectName("roastLineEdit")
        self.typeLineEdit = QtWidgets.QLineEdit(addEditCoffeeForm)
        self.typeLineEdit.setGeometry(QtCore.QRect(160, 80, 211, 21))
        self.typeLineEdit.setObjectName("typeLineEdit")
        self.descriptionLineEdit = QtWidgets.QLineEdit(addEditCoffeeForm)
        self.descriptionLineEdit.setGeometry(QtCore.QRect(160, 100, 211, 21))
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.priceLineEdit = QtWidgets.QLineEdit(addEditCoffeeForm)
        self.priceLineEdit.setGeometry(QtCore.QRect(160, 230, 51, 21))
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.volumeLineEdit = QtWidgets.QLineEdit(addEditCoffeeForm)
        self.volumeLineEdit.setGeometry(QtCore.QRect(330, 230, 51, 21))
        self.volumeLineEdit.setObjectName("volumeLineEdit")

        self.retranslateUi(addEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(addEditCoffeeForm)

    def retranslateUi(self, addEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        addEditCoffeeForm.setWindowTitle(_translate("addEditCoffeeForm", "Редактировать запись"))
        self.saveButton.setText(_translate("addEditCoffeeForm", "Сохранить"))
        self.label.setText(_translate("addEditCoffeeForm", "ID"))
        self.label_2.setText(_translate("addEditCoffeeForm", "Название"))
        self.label_3.setText(_translate("addEditCoffeeForm", "Степень обжарки"))
        self.label_4.setText(_translate("addEditCoffeeForm", "Молотый/в зёрнах"))
        self.label_5.setText(_translate("addEditCoffeeForm", "Описание"))
        self.label_6.setText(_translate("addEditCoffeeForm", "Цена"))
        self.label_7.setText(_translate("addEditCoffeeForm", "Объём уп."))
