# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(850, 500)
        self.coffeeDB = QtWidgets.QTableWidget(Widget)
        self.coffeeDB.setGeometry(QtCore.QRect(20, 50, 811, 441))
        self.coffeeDB.setObjectName("coffeeDB")
        self.coffeeDB.setColumnCount(0)
        self.coffeeDB.setRowCount(0)
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(30, 20, 281, 16))
        self.label.setObjectName("label")
        self.addButton = QtWidgets.QPushButton(Widget)
        self.addButton.setGeometry(QtCore.QRect(690, 20, 141, 32))
        self.addButton.setObjectName("addButton")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "База данных \"Дискофектикут\""))
        self.label.setText(_translate("Widget", "Просмотр данных о кофе"))
        self.addButton.setText(_translate("Widget", "Добавить запись"))
